[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aibedo"
authors = [{name = "Kalai Ramea", email = "kramea@parc"}]
dynamic = ["version", "description"]
